# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nl2B_RzJIiiIB7-qOR_PSL9az6cEEBFQ
"""

!pip install xgboost

import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score

data_class_1 = pd.read_csv("ICMP_data_class_1.csv", header=None, names=["curr_derivative", "mean", "measurement_class"])
data_class_0 = pd.read_csv("ICMP_data_class_0.csv", header=None, names=["curr_derivative", "mean", "measurement_class"])

data = pd.concat([data_class_1, data_class_0], ignore_index=True)
X = data[["curr_derivative", "mean"]]  # Features
y = data["measurement_class"]  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = xgb.XGBClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

with open('XGBOOST.dat', 'wb') as f:
    pickle.dump(model, f)